## Numpy

Импортировать NumPy под именем np

In [2]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [3]:
vector0 = np.zeros(10, dtype='int')
vector0


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Создать вектор размера 10, заполненный единицами

In [6]:
vector1 = np.ones(10)
print(vector1)
vector_ones = np.ones(10, dtype='int')
print(vector_ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1]


Создать вектор размера 10, заполненный числом 2.5

In [8]:
vector_2 = np.full(10, 2.5)
print(vector_2)
vector_two = np.full(10, 2.5, dtype='float')
print(vector_two)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]
[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [9]:
vector_ten = np.zeros(10)
vector_ten[4] = 1
print(vector_ten)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Развернуть вектор (первый становится последним)

In [13]:
vector_direct = np.linspace(2.0, 20.0,num = 10) # числа - по возрастанию
vector_4 = vector_direct[::-1]
vector_4 # теперь числа - в убывающем порядке

vector_reverse = np.arange(20, dtype='float')
value = vector_reverse[::-1]
print(value)

[19. 18. 17. 16. 15. 14. 13. 12. 11. 10.  9.  8.  7.  6.  5.  4.  3.  2.
  1.  0.]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [17]:
array_2d = np.arange(0,9).reshape(3,3) # форма 2*2, но это все еще array
matrix_1 = np.asmatrix(array_2d) # преобразуем к matrix
print(matrix_1)

array_2d2 = np.arange(0, 9).reshape(3, 3)
print(array_2d2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [19]:
# решение 1
source = [1,2,0,0,4,0]
non_zeros = []

for i in range(0, len(source)):
    if source[i] != 0:
        non_zeros.append(i)

print(non_zeros)

source2 = [1,2,3,4,5,6,0,8,0,7,0,5,0,1,3,0]
without_zeros = []
for i in range(len(source2)):
    if source2[i] != 0:
        without_zeros.append(i)
print(without_zeros)

[0, 1, 4]
[0, 1, 2, 3, 4, 5, 7, 9, 11, 13, 14]


In [20]:
# решение 2
source = [1,2,0,0,4,0]
non_zeros = []

for index,value in enumerate(source):
    if(value != 0):
        non_zeros.append(index)

non_zeros

[0, 1, 4]

In [21]:
# решение 3
source = [1,2,0,0,4,0]
non_zeros = np.nonzero(source)
print(non_zeros)
source2 = [1,2,3,4,5,6,0,8,0,7,0,5,0,1,3,0]
non_zero = np.nonzero(source2)
print(non_zero)

(array([0, 1, 4], dtype=int64),)
(array([ 0,  1,  2,  3,  4,  5,  7,  9, 11, 13, 14], dtype=int64),)


Создать 3x3 единичную матрицу

In [25]:
matrix_ones = np.asmatrix( np.ones(3*3).reshape(3,3) )
print(matrix_ones)
matrix_ones2 = np.ones(3 * 3).reshape(3, 3)
print(matrix_ones2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Создать массив 3x3x3 со случайными значениями

In [28]:
# решение 1
def random_value(x,y,z):
    return np.random.rand(1)[0]
    
array_random_3 = np.fromfunction(np.vectorize(random_value), (3, 3, 3))
print(array_random_3)
array_random = np.random.rand(3, 3, 3)
print(array_random)

[[[0.19107391 0.55683736 0.87244832]
  [0.18135394 0.53894435 0.73599461]
  [0.36196498 0.11691695 0.00613971]]

 [[0.35099848 0.45190742 0.30664057]
  [0.51586011 0.57985656 0.00949456]
  [0.90510769 0.86553797 0.9026388 ]]

 [[0.47128464 0.69344163 0.82394739]
  [0.2043243  0.64494472 0.28741834]
  [0.63883716 0.58050581 0.39358616]]]
[[[0.60984395 0.07831531 0.57833657]
  [0.77626742 0.13414511 0.93506521]
  [0.80245402 0.49061508 0.09253088]]

 [[0.05198783 0.90377693 0.89314158]
  [0.29313762 0.48157777 0.22904927]
  [0.9053221  0.33741858 0.1649056 ]]

 [[0.39573606 0.88951072 0.59057292]
  [0.91872553 0.69550885 0.1264756 ]
  [0.97544165 0.32671011 0.45949165]]]


In [13]:
# решение 2
array_random_3 = np.random.rand(3,3,3) # то же самое: np.random.random((3,3,3))
array_random_3

array([[[0.30304629, 0.43341066, 0.28713713],
        [0.92656348, 0.6613318 , 0.26027959],
        [0.98272187, 0.84738208, 0.1393213 ]],

       [[0.86470181, 0.71224362, 0.03914699],
        [0.5650913 , 0.73959756, 0.52213175],
        [0.66622885, 0.95969695, 0.5712402 ]],

       [[0.28141643, 0.02208693, 0.49026649],
        [0.61828124, 0.15831984, 0.13696301],
        [0.10641165, 0.13348891, 0.12576553]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [29]:
vect_30 = np.random.rand(30)
print(vect_30)
result_avg = np.average(vect_30) # np.mean(vect_30) - то же самое
result_avg
vector = np.random.rand(30)
vector.mean()
print(vector)

[0.37232255 0.58641108 0.57288521 0.15501336 0.991321   0.65071512
 0.36648883 0.4922739  0.8864328  0.30886197 0.73636435 0.56034379
 0.72008999 0.04270169 0.22275517 0.89244925 0.50876924 0.98670055
 0.29907573 0.61977252 0.90663984 0.19801276 0.19161783 0.03969275
 0.717564   0.37449017 0.46762141 0.0037189  0.43012963 0.9453143 ]
[0.46778589 0.66440619 0.77934693 0.43931646 0.80752102 0.70693052
 0.27847266 0.22387905 0.18652091 0.7222074  0.56803297 0.52305731
 0.37383479 0.56409734 0.42184785 0.64178132 0.96037587 0.09727896
 0.64731667 0.32098351 0.62676103 0.77537127 0.02765124 0.84105856
 0.37589892 0.74874463 0.56822419 0.38073803 0.11747546 0.97097578]


Перемножить матрицы 5x3 и 3x2

In [30]:
matrix_1 = np.asmatrix(np.random.rand(5,3))
matrix_2 = np.asmatrix(np.random.rand(3,2))

result_matrix = matrix_1 * matrix_2 # как вариант:  np.dot(matrix_1, matrix_2)

result_matrix

matrix([[0.57306605, 0.76896644],
        [0.40334036, 0.56561543],
        [0.73426195, 1.0658667 ],
        [0.81853683, 1.31003474],
        [0.69675188, 0.93841669]])

Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [31]:
result_vector = np.linspace(0,1,11, endpoint=False)[1:]
result_vector

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

Заменить максимальный элемент на ноль

In [32]:
source_vector = np.linspace(1,2,10, endpoint=False)
source_vector[3] = sum(source_vector) # сделаем так, чтобы max_value - было где-то в центре
source_vector[source_vector.argmax()] = 0
source_vector

array([1. , 1.1, 1.2, 0. , 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

Преобразовать массив из float в int

In [33]:
source_array = np.arange(10, dtype=np.float32)
result_array = source_array.astype(np.int64, copy = False)

source_array, result_array

(array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64))

Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [34]:
source_coords = np.random.random((10,2))

import scipy.spatial
distances = scipy.spatial.distance.cdist(source_coords, source_coords, metric='euclidean')
 
distances

array([[0.        , 0.4728996 , 0.60396373, 0.55894747, 0.50412264,
        0.36322358, 0.196074  , 0.21839097, 0.63662628, 0.2225533 ],
       [0.4728996 , 0.        , 0.87125787, 0.38566425, 0.93113574,
        0.18250611, 0.58905737, 0.65156182, 0.69708086, 0.62055694],
       [0.60396373, 0.87125787, 0.        , 0.62167078, 0.36708149,
        0.87450229, 0.75614407, 0.72308619, 0.33431952, 0.39283347],
       [0.55894747, 0.38566425, 0.62167078, 0.        , 0.82590021,
        0.51092217, 0.74633856, 0.77732433, 0.35123504, 0.5616697 ],
       [0.50412264, 0.93113574, 0.36708149, 0.82590021, 0.        ,
        0.86011721, 0.56585759, 0.503787  , 0.65098553, 0.31066121],
       [0.36322358, 0.18250611, 0.87450229, 0.51092217, 0.86011721,
        0.        , 0.43321927, 0.50313132, 0.76801226, 0.55636821],
       [0.196074  , 0.58905737, 0.75614407, 0.74633856, 0.56585759,
        0.43321927, 0.        , 0.07738787, 0.82854176, 0.3639186 ],
       [0.21839097, 0.65156182, 0.7230861

Случайно расположить p элементов в 2D массив

In [35]:
# условие
p = 5
n = 3
m = 3
elements = np.random.random(p) # элементы, которые располагать
result = np.zeros((n,m)) # массив, в который располагать элементы

np.put(result, np.random.choice(range(n*m), p, replace=False),  elements)
result

array([[0.59865641, 0.23377447, 0.98799799],
       [0.        , 0.        , 0.52910013],
       [0.        , 0.93922198, 0.        ]])

Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [36]:
source = np.array([1,2,3,4,5]) # исходный массив
zero_count = 3 # кол-во нулей, которые располагать между элементами
result = np.zeros(len(source) + (len(source)-1)*(zero_count)) # итоговый массив: создаем из нулей, и потом заменим нужные элементы из source
result[::zero_count+1] = source # каждый элемент, который выпадает не на 0 - подставляем из исходного масива

result

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

Найти наиболее частое значение в массиве

In [37]:
source = np.random.randint(low = 4, high = 9, size = 10) # числа: min = low, max = high - 1. Всего 10 чисел
occurances = np.bincount(source) # значение i-го элемента в массиве = кол-во раз, которое встречалось число i
print(occurances)
max_frequent = occurances.argmax() # в каком элементе массива наибольшее значение

max_frequent

[0 0 0 0 1 2 0 5 2]


7

Найти n наибольших значений в массиве

In [38]:
# решение = отсортировать по убыванию и взять первые n элементов
n = 5
source = np.random.randint(low = 1, high = 10, size = 15)
print(source)
sorted_array = np.flip(np.sort(source))
print(sorted_array)
result_array = sorted_array[:n]

result_array

[7 9 2 2 6 4 7 8 8 4 1 8 1 7 3]
[9 8 8 8 7 7 7 6 4 4 3 2 2 1 1]


array([9, 8, 8, 8, 7])

## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [39]:
import pandas as pd

In [40]:
# en_openfoodfacts_org_products.tsv
#food = pd.read_csv('../../data.csv', delimiter='\t', encoding='utf-8', low_memory=False) # для загрузки нескольких строк - можно указать nrows=5
food = pd.read_csv('../../data.csv', delimiter='\t', low_memory=False)

Посмотреть первые 5 записей

In [41]:
food.head()

code                                                url  \
0  0000000003087  http://world-en.openfoodfacts.org/product/0000...   
1  0000000004530  http://world-en.openfoodfacts.org/product/0000...   
2  0000000004559  http://world-en.openfoodfacts.org/product/0000...   
3  0000000016087  http://world-en.openfoodfacts.org/product/0000...   
4  0000000016094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957   2017-03-09T14:32:37Z  Banana Chips Sweetened (Whole)   
2      1489069957   2017-03-09T14:32:37Z                         Peanuts   
3      1489055731   2017-03-09T10:35:31Z          Organic Salted Nut Mix   
4      1489055653   2017-03-09T10:34:13Z                 Organic Polenta   

  generic_name quantity  ... fruits-vegetables-nuts_100g  \
0          NaN      1kg  ...                         NaN   
1          NaN      NaN  ...                         NaN   
2          NaN      NaN  ...                         NaN   
3          NaN      NaN  ...                         NaN   
4          NaN      NaN  ...                         NaN   

  fruits-vegetables-nuts-estimate_100g collagen-meat-protein-ratio_100g  \
0                                  NaN                              NaN   
1                                  NaN                              NaN   
2                                  NaN                              NaN   
3                                  NaN                              NaN   
4                                  NaN                              NaN   

  cocoa_100g chlorophyl_100g carbon-footprint_100g nutrition-score-fr_100g  \
0        NaN             NaN                   NaN                     NaN   
1        NaN             NaN                   NaN                    14.0   
2        NaN             NaN                   NaN                     0.0   
3        NaN             NaN                   NaN                    12.0   
4        NaN             NaN                   NaN                     NaN   

  nutrition-score-uk_100g glycemic-index_100g water-hardness_100g  
0                     NaN                 NaN                 NaN  
1                    14.0                 NaN                 NaN  
2                     0.0                 NaN                 NaN  
3                    12.0                 NaN                 NaN  
4                     NaN                 NaN                 NaN  

[5 rows x 163 columns]

Сколько наблюдений в наборе данных?


In [43]:
print(food.shape[0]) # вариант 1, наиболее понятный
print(food.iloc[:,5].count()) # вариант 2, но, тут нужно проверять, что нет пропусков - например, для первых столбцов результат отображает меньший
len(food.index) # вариант 3, наиболее быстрый по скорости выполнения: https://stackoverflow.com/questions/15943769/how-do-i-get-the-row-count-of-a-pandas-dataframe
print(food.shape[0])
len(food.index)
print(food.shape[0])

356027
356027
356027
356027


Сколько столбцов в наборе данных?

In [46]:
food.columns.size

163

Напечатайте все названия столбцов

In [48]:
print(food.columns.values)

['code' 'url' 'creator' 'created_t' 'created_datetime' 'last_modified_t'
 'last_modified_datetime' 'product_name' 'generic_name' 'quantity'
 'packaging' 'packaging_tags' 'brands' 'brands_tags' 'categories'
 'categories_tags' 'categories_en' 'origins' 'origins_tags'
 'manufacturing_places' 'manufacturing_places_tags' 'labels' 'labels_tags'
 'labels_en' 'emb_codes' 'emb_codes_tags' 'first_packaging_code_geo'
 'cities' 'cities_tags' 'purchase_places' 'stores' 'countries'
 'countries_tags' 'countries_en' 'ingredients_text' 'allergens'
 'allergens_en' 'traces' 'traces_tags' 'traces_en' 'serving_size'
 'no_nutriments' 'additives_n' 'additives' 'additives_tags' 'additives_en'
 'ingredients_from_palm_oil_n' 'ingredients_from_palm_oil'
 'ingredients_from_palm_oil_tags'
 'ingredients_that_may_be_from_palm_oil_n'
 'ingredients_that_may_be_from_palm_oil'
 'ingredients_that_may_be_from_palm_oil_tags' 'nutrition_grade_uk'
 'nutrition_grade_fr' 'pnns_groups_1' 'pnns_groups_2' 'states'
 'states_tags' 

Какое название у 105 столбца?

In [49]:
food.columns[104]

'-glucose_100g'

Какой тип наблюдений в 105 столбце?

In [53]:
food.dtypes[104]

dtype('float64')

Как проиндексирован набор данных?

In [54]:
print(food.index)

RangeIndex(start=0, stop=356027, step=1)


Каково значение имени продукта в 19-м наблюдении?

In [58]:
food.iloc[18].loc['product_name']
food.iloc[0].loc['code']

'0000000003087'

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [59]:
import pandas as pd
import requests
import io

In [60]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'

r = requests.get(url)
if r.ok:
    data = r.content.decode('utf8')
    chipo = pd.read_csv(io.StringIO(data), delimiter='\t',encoding='utf-8', low_memory=False)
    
chipo.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

Как много продуктов стоят более чем $10.00?

In [65]:
chipo['item_price_float'] = chipo['item_price'].map(lambda price: float(price[1:]))
filter = chipo[chipo['item_price_float'] > 10.00]
len(filter)

1130

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [67]:
print(chipo.loc[:, ['item_name', 'item_price']])

                                  item_name item_price
0              Chips and Fresh Tomato Salsa     $2.39 
1                                      Izze     $3.39 
2                          Nantucket Nectar     $3.39 
3     Chips and Tomatillo-Green Chili Salsa     $2.39 
4                              Chicken Bowl    $16.98 
...                                     ...        ...
4617                          Steak Burrito    $11.75 
4618                          Steak Burrito    $11.75 
4619                     Chicken Salad Bowl    $11.25 
4620                     Chicken Salad Bowl     $8.75 
4621                     Chicken Salad Bowl     $8.75 

[4622 rows x 2 columns]


Отсортировать по имени предмета

In [68]:
chipo.sort_values(by=['item_name'])

order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink   
341        148         1  6 Pack Soft Drink   
1849       749         1  6 Pack Soft Drink   
1860       754         1  6 Pack Soft Drink   
2713      1076         1  6 Pack Soft Drink   
...        ...       ...                ...   
2384       948         1  Veggie Soft Tacos   
781        322         1  Veggie Soft Tacos   
2851      1132         1  Veggie Soft Tacos   
1699       688         1  Veggie Soft Tacos   
1395       567         1  Veggie Soft Tacos   

                                     choice_description item_price  \
3389                                        [Diet Coke]    $12.98    
341                                         [Diet Coke]     $6.49    
1849                                             [Coke]     $6.49    
1860                                        [Diet Coke]     $6.49    
2713                                             [Coke]     $6.49    
...                                                 ...        ...   
2384  [Roasted Chili Corn Salsa, [Fajita Vegetables,...     $8.75    
781   [Fresh Tomato Salsa, [Black Beans, Cheese, Sou...     $8.75    
2851  [Roasted Chili Corn Salsa (Medium), [Black Bea...     $8.49    
1699  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...    $11.25    
1395  [Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...     $8.49    

      item_price_float  
3389             12.98  
341               6.49  
1849              6.49  
1860              6.49  
2713              6.49  
...                ...  
2384              8.75  
781               8.75  
2851              8.49  
1699             11.25  
1395              8.49  

[4622 rows x 6 columns]

Сколько было заказано самого дорогого предмета?

In [60]:
# трактовака условия 1:
#   в данных нет идентификатора предмета,
#   то есть, с одним названием - могут встречаться разные предметы.
#   Например, название совпадает, но цена разная - это разные предметы
# решение 1:
#   отсортировать по цене, взять первый.
#   Взять значение из столбца quantity
#   Ограничение: считаем, что только 1 запись с максимальной ценой
chipo_sorted = chipo.sort_values(by=['item_price_float'], ascending=False)
chipo_sorted.head()
top_price = chipo_sorted.iloc[0,5]
row_of_interest = chipo_sorted[chipo_sorted['item_price_float'] == top_price]
assert len(row_of_interest) == 1
row_of_interest.iloc[0, 1]


15

In [61]:
# трактовка условия 2: 
#   считаем, что идентификатор предмета - его название,
#   и в других заказах этот предмет может быть с другой ценой.
# решение:
#   отсортировать по цене, взять первый, его название.
#   Теперь из всего набора выбрать записи, в которых такой предмет.
#   Просуммировать quantity.
chipo_sorted = chipo.sort_values(by=['item_price_float'], ascending=False)
top_item = chipo.sort_values(by=['item_price_float'], ascending=False).iloc[0,2] # если указать через loc - тогда не понятно как отметить первую строку, т.к. считает 0 как название
rows_of_interest = chipo[chipo['item_name']==top_item]
total_count = sum(rows_of_interest.loc[:,'quantity'])

total_count

130

Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [62]:
rows_of_interest = chipo[chipo['item_name'] == 'Veggie Salad Bowl']
# Решение 1: кол-во предметов, которые заказали в сумме
print(sum(rows_of_interest['quantity']))
# Решение 2: кол-во раз (строк), в которых заказывают этот предмет
len(rows_of_interest)

18


18

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [63]:
rows_of_interest = chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)]
len(rows_of_interest)

20

In [64]:
print('The End!')

The End!
