## Numpy

Импортировать NumPy под именем np

In [1]:
import numpy as np

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [2]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Создать вектор размера 10, заполненный единицами

In [3]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Создать вектор размера 10, заполненный числом 2.5

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [5]:
num = np.zeros(10)
num[4] = 1
print(num)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Развернуть вектор (первый становится последним)

In [6]:
vector = np.arange(10)
print(vector[::-1])

[9 8 7 6 5 4 3 2 1 0]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [7]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [8]:
z = np.nonzero([1, 2, 0, 0, 4, 0])
print(z)

(array([0, 1, 4]),)


Создать 3x3 единичную матрицу

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Создать массив 3x3x3 со случайными значениями

In [10]:
np.random.random((3, 3, 3))

array([[[0.7395362 , 0.18606073, 0.88297549],
        [0.3844145 , 0.17936249, 0.19348951],
        [0.47892153, 0.80731907, 0.90920339]],

       [[0.71150634, 0.86970998, 0.75798589],
        [0.22173186, 0.31196487, 0.54136707],
        [0.57953074, 0.77842047, 0.63328584]],

       [[0.0832418 , 0.46428415, 0.29591143],
        [0.12127688, 0.06805694, 0.01544638],
        [0.67571021, 0.17809825, 0.93811341]]])

Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [11]:
z = np.random.random(30)
z2 = z.mean()
print(z2)

0.39178245831127934


Перемножить матрицы 5x3 и 3x2

In [12]:
z = np.dot(np.ones((5, 3)), np.ones((3, 2)))
print(z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [13]:
z = np.linspace(0, 1, 12)[1:-1]
z[z.argmax()] = 0
print(z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.        ]


Заменить максимальный элемент на ноль

Преобразовать массив из float в int

In [14]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [15]:
import scipy.spatial
z = np.random.random((10, 2))
d = scipy.spatial.distance.cdist(z, z)
print(d)

[[0.         0.54060726 0.93910251 0.70280021 0.6255684  0.53701852
  0.54517209 0.3603755  0.77274614 0.72501892]
 [0.54060726 0.         0.41047216 0.32804611 0.28110431 0.16548426
  0.55793822 0.20188827 0.45241168 0.33090661]
 [0.93910251 0.41047216 0.         0.35560436 0.4005598  0.51045872
  0.75901272 0.58008521 0.43167038 0.32917756]
 [0.70280021 0.32804611 0.35560436 0.         0.07724188 0.49305659
  0.40515008 0.36650688 0.1266437  0.02821518]
 [0.6255684  0.28110431 0.4005598  0.07724188 0.         0.44596405
  0.36220729 0.29207229 0.17844922 0.10059643]
 [0.53701852 0.16548426 0.51045872 0.49305659 0.44596405 0.
  0.69205061 0.28523248 0.61783868 0.49464385]
 [0.54517209 0.55793822 0.75901272 0.40515008 0.36220729 0.69205061
  0.         0.41781516 0.37790367 0.4327956 ]
 [0.3603755  0.20188827 0.58008521 0.36650688 0.29207229 0.28523248
  0.41781516 0.         0.46349986 0.38399212]
 [0.77274614 0.45241168 0.43167038 0.1266437  0.17844922 0.61783868
  0.37790367 0.46349

Случайно расположить p элементов в 2D массив

In [16]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [17]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


Найти наиболее частое значение в массиве

In [18]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())


0


Найти n наибольших значений в массиве

In [19]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 100

print (Z[np.argpartition(-Z,n)[:n]])

[9976 9955 9971 9988 9950 9957 9970 9942 9999 9990 9946 9952 9979 9986
 9974 9984 9998 9941 9956 9994 9958 9964 9944 9989 9996 9943 9954 9968
 9973 9969 9940 9959 9997 9962 9947 9966 9951 9991 9948 9975 9982 9978
 9972 9965 9983 9987 9961 9960 9963 9945 9992 9953 9967 9980 9977 9993
 9949 9985 9981 9995 9939 9934 9925 9938 9923 9920 9926 9927 9932 9919
 9917 9922 9921 9930 9936 9935 9937 9929 9928 9933 9931 9918 9924 9916
 9910 9908 9906 9914 9911 9907 9905 9913 9902 9903 9904 9909 9912 9915
 9901 9900]


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [ ]:
import pandas as pd
data = pd.read_csv('../../data.csv', sep='\t')

Посмотреть первые 5 записей

In [ ]:
data.head()

Сколько наблюдений в наборе данных?


In [22]:
data.index.value_counts()

2047     1
96890    1
80498    1
78451    1
68212    1
        ..
17826    1
19875    1
30116    1
32165    1
0        1
Length: 356027, dtype: int64

Сколько столбцов в наборе данных?

In [23]:
data.columns

Index(['code', 'url', 'creator', 'created_t', 'created_datetime',
       'last_modified_t', 'last_modified_datetime', 'product_name',
       'generic_name', 'quantity',
       ...
       'fruits-vegetables-nuts_100g', 'fruits-vegetables-nuts-estimate_100g',
       'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g',
       'carbon-footprint_100g', 'nutrition-score-fr_100g',
       'nutrition-score-uk_100g', 'glycemic-index_100g',
       'water-hardness_100g'],
      dtype='object', length=163)

Напечатайте все названия столбцов

Какое название у 105 столбца?

Какой тип наблюдений в 105 столбце?

Как проиндексирован набор данных?

Каково значение имени продукта в 19-м наблюдении?

## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

Как много продуктов стоят более чем $10.00?

Какова цена каждого предмета? Напечатать столбцы item_name и item_price

Отсортировать по имени предмета

Сколько было заказано самого дорогого предмета?

Сколько раз был заказан предмет "Veggie Salad Bowl"?

Сколько раз люди заказали более чем 1 предмет "Canned Soda"?